FROM centos
# RUN npm set registry=http://npm-registry.kemao-dev.com/
# COPY ./volume/etc/hosts /etc/hosts
COPY ./volume/home/nodejs/node-v6.10.3-linux-x64.tar.gz /home/nodejs/node-v6.10.3-linux-x64.tar.gz
