FROM docker-registry.kemao-inc.com/kemao-dev/gitlab-runner:1.0.0

# ENV PATH=$PATH:/home/nodejs/node-v8.9.1-linux-x64/bin

# ADD ./volume/root /root
# RUN eval "$(ssh-agent -s)" && \
# chmod 0600 /root/.ssh/id_rsa && \
# ssh-add /root/.ssh/id_rsa > /dev/null
# RUN ssh git@github.com -o StrictHostKeyChecking=no>~/git.txt
