FROM docker-registry.kemao-inc.com/centos

RUN curl -L https://packages.gitlab.com/install/repositories/runner/gitlab-ci-multi-runner/script.rpm.sh | sudo bash
RUN yum install gitlab-ci-multi-runner -y
# RUN gitlab-ci-multi-runner register 
